### ISSUE TITLE
代理功能无法保存

### ISSUE THREAD

**Issue by guozil1** [peacefulprogram/nivod-tv#3]
搜索功能也无法使用，建议支持首字母搜索，可以用百度的API
https://[haokan.baidu.com/haokan/ui-search/pc/sug?query=fczx](https://haokan.baidu.com/haokan/ui-search/pc/sug?query=fczx)

**Comment by peacefulprogram** [comment]
无法复现

**Comment by peacefulprogram** [comment]
无法复现
